### ISSUE TITLE
Not usable as a modpack

### ISSUE THREAD

**Issue by lordtoran** [DevynCJohnson/DCJ-Minetest-Mods#1]
I cannot git clone the mod collection as is into my Minetest mods folder without complaints from the game. What works for me is to cd into the folder, do a "touch modpack.txt" and renaming the folder to "dcj_minetest_mods".

**Comment by HybridDog** [comment]
you could also do "ln -r -s ../DCJ-Minetest-Mods/currency currency"

**Comment by lordtoran** [comment]
Well, my updater script goes over the "games", "mods", "textures" and a custom "inactive_mods" folders and does a git pull (+submodules) in all contained subfolders. Maybe I'll create a "modpacks" folder that can be kept current via git too, and mods (or the whole modpack) could be symlinked as you suggested in order to activate.

It would be nice if the author could provide the mods separately. I couldn't find a fork of any of them.

**Comment by DevynCJohnson** [comment]
Sorry for the delay.

This is not a mod-pack. The description for this old project says "Each folder is a separate Minetest mod". You must take the mods out of the folder.

**Comment by DevynCJohnson** [comment]
As for having them as separate projects, I could not do that at the time I uploaded the mods. At the time, GitHub would only allow me to have five projects, so I placed those mods into one folder (not as a modpack).
